name: Promote to Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # TODO: version promotion
        description: 'TODO: proper automatic semver bumping'
        # Default value if no value is explicitly provided
        default: '0.0.1'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Merge and Push to Release
      run: |
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        
        # main
        git fetch --unshallow
        git status

        # release
        git checkout release
        git merge --ff-only origin/release-elect
        git push
